[package]
name = "rbkcrack"
version = "0.1.0"
authors = ["Aloxaf <bailong104@gmail.com>"]

[dependencies]
failure = "0.1.2"
clap = {version = "^2.32.0", features = ["yaml"]}
chrono = "0.4.6"
zip = { git = "https://github.com/Aloxaf/zip-rs" }
